// src/config/reportConfig.js

export const REPORT_CONFIG = {

    bookings: {

        title: "Booking Report",

        subtitle: "Booking history of Guest House applications.",

        exportFileName: "Booking_Report",

        summaryCards: [
            "Total Bookings",
            "Approved",
            "Pending",
            "Rejected"
        ],

        filters: [
            "fromDate",
            "toDate",
            "guestHouse",
            "bookingStatus",
            "guestType"
        ],

        columns: [

            {
                header: "Booking No",
                accessor: "GHRBookingNo"
            },

            {
                header: "Guest Name",
                accessor: "GuestName"
            },

            {
                header: "Guest House",
                accessor: "GuestHouseName"
            },

            {
                header: "Arrival",
                accessor: "ArrivalDateTime"
            },

            {
                header: "Departure",
                accessor: "DepartureDateTime"
            },

            {
                header: "Status",

                accessor: "BookingStatus",

                render: (row) => (

                    <span
                        className={`status ${row.BookingStatus}`}
                    >
                        {row.BookingStatus}
                    </span>

                )
            }

        ]

    },

    occupancy: {

        title: "Occupancy Report",

        subtitle: "Current room occupancy of all guest houses.",

        exportFileName: "Occupancy_Report",

        summaryCards: [

            {
                title: "Total Rooms",
                key: "TotalRooms"
            },

            {
                title: "Occupied",
                key: "Occupied"
            },

            {
                title: "Available",
                key: "Available"
            },

            {
                header: "Occupancy",

                accessor: "OccupancyPercentage",

                render: (row) => (

                    `${row.OccupancyPercentage}%`

                )
            }

        ],

        filters: [
            "guestHouse"
        ],

        columns: [

            {
                header: "Guest House",
                accessor: "GuestHouseName"
            },

            {
                header: "Total Rooms",
                accessor: "TotalRooms"
            },

            {
                header: "Occupied",
                accessor: "OccupiedRooms"
            },

            {
                header: "Available",
                accessor: "AvailableRooms"
            },

            {
                header: "Maintenance",
                accessor: "MaintenanceRooms"
            },

            {
                header: "Occupancy %",
                accessor: "OccupancyPercentage"
            }

        ]
    },

    revenue: {

        title: "Revenue Report",

        subtitle: "Revenue generated by Guest Houses.",

        exportFileName: "Revenue_Report",

        summaryCards: [
            "Total Revenue",
            "Collected",
            "Pending"
        ],

        filters: [

            {
                field: "guestHouse",
                type: "select",
                label: "Guest House",
                master: "guestHouses"
            },

            {
                field: "guestType",
                type: "select",
                label: "Guest Type",
                master: "guestTypes"
            },

            {
                field: "fromDate",
                type: "date",
                label: "From Date"
            }

        ],

        columns: [

            {
                header: "Guest House",
                accessor: "GuestHouseName"
            },

            {
                header: "Bookings",
                accessor: "TotalBookings"
            },

            {
                header: "Revenue",

                accessor: "Revenue",

                render: (row) => (

                    <>₹ {row.Revenue}</>

                )
            },

            {
                header: "Collected",
                accessor: "CollectedAmount"
            },

            {
                header: "Pending",
                accessor: "PendingAmount"
            }

        ]

    },

    guestStatistics: {

        title: "Guest Statistics",

        subtitle: "Guest category-wise booking statistics.",

        exportFileName: "Guest_Statistics",

        summaryCards: [
            "Total Guests",
            "Average Stay"
        ],

        filters: [
            "fromDate",
            "toDate"
        ],

        columns: [

            {
                header: "Guest Type",
                accessor: "GuestTypeName"
            },

            {
                header: "Bookings",
                accessor: "TotalBookings"
            },

            {
                header: "Guests",
                accessor: "TotalGuests"
            },

            {
                header: "Average Stay",
                accessor: "AverageStay"
            }

        ]

    },

    roomUtilization: {

        title: "Room Utilization",

        subtitle: "Room utilization analysis.",

        exportFileName: "Room_Utilization",

        summaryCards: [
            "Total Rooms",
            "Utilized"
        ],

        filters: [
            "guestHouse"
        ],

        columns: [

            {
                header: "Room No",
                accessor: "GHRoomNo"
            },

            {
                header: "Guest House",
                accessor: "GuestHouseName"
            },

            {
                header: "Occupied Days",
                accessor: "OccupiedDays"
            },

            {
                header: "Vacant Days",
                accessor: "VacantDays"
            },

            {
                header: "Occupancy %",
                accessor: "OccupancyPercentage"
            }

        ]

    }

};